# Generated by Django 4.2.29 on 2026-03-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_entry_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date', 'order', '-created_at'], 'verbose_name_plural': 'Time entries'},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within same date (lower = higher in list)'),
        ),
    ]
